version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: gunicorn -w 4 -b 127.0.0.1:5000 app:app
    volumes:
      - .:/app
    working_dir: /app
    links:
      - redis
      - db
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /home/ubuntu/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myweb
      MYSQL_USER: myweb
      MYSQL_PASSWORD: T3KfkTjGmXE1ar5p
  redis:
    image: redis:6